### ISSUE TITLE
插件不支持.flac文件

### ISSUE THREAD

**Issue by xSILENCEx** [boyan01/flutter-music-player#13]
大佬，这个插件不支持flac格式吗？

```
W/MediaAnalyticsItem(31974): Unable to record: (codec:0:-1:-11:0:5:android.media.mediacodec.codec=OMX.google.mp3.decoder:android.media.mediacodec.mode=audio:android.media.mediacodec.secure=0:android.media.mediacodec.mime=audio/mpeg:android.media.mediacodec.bytesin=1563167:) [forcenew=0]
I/flutter (31974): load image for 11334 , 有你
I/flutter (31974): get media play uri : 11334 , /storage/emulated/0/netease/cloudmusic/Music/王愚 陈娅琪 - 有你 .flac
I/flutter (31974): load image for 11334 , 有你
I/flutter (31974): load image for 11334 , 有你
E/ExoPlayerImplInternal(31974): Source error.
E/ExoPlayerImplInternal(31974): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
E/ExoPlayerImplInternal(31974): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
E/ExoPlayerImplInternal(31974): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
E/ExoPlayerImplInternal(31974): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(31974): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ExoPlayerImplInternal(31974): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ExoPlayerImplInternal(31974): 	at java.lang.Thread.run(Thread.java:764)
I/flutter (31974): load image for 11334 , 有你
I/flutter (31974): load image for 11334 , 有你
```

**Comment by boyan01** [comment]
看起来应该是的，就是不知道直接引入这些 extractors 合不合适。

我研究一下flutter plugin 能不能支持 addition plugin 吧。
